from typing import TypeAlias
__typ0 : TypeAlias = "bytes"
__typ1 : TypeAlias = "Response"
# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:23

import io
import logging
import os
import urllib
from mimetypes import guess_type
from typing import Dict, Optional, Text, Tuple, Union

import requests
from boto.s3.connection import S3Connection
from boto.s3.key import Key
from django.conf import settings
from django.db import migrations, models
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps
from PIL import Image, ImageOps
from requests import ConnectionError, Response

def __tmp5(s: Union[Text, __typ0], encoding: Text='utf-8') :
    """converts a string to a native string"""
    if isinstance(s, str):
        return s
    elif isinstance(s, Text):
        return s.encode(str(encoding))
    elif isinstance(s, __typ0):
        return s.decode(encoding)
    else:
        raise TypeError("force_str expects a string type")


class Uploader:
    def __init__(__tmp2) -> None:
        __tmp2.path_template = "{realm_id}/emoji/{emoji_file_name}"
        __tmp2.emoji_size = (64, 64)

    def upload_files(__tmp2, __tmp6, __tmp8,
                     __tmp11) -> None:
        raise NotImplementedError()

    def get_dst_path_id(__tmp2, realm_id, url: Text, __tmp4) :
        _, image_ext = os.path.splitext(url)
        file_name = ''.join((__tmp4, image_ext))
        return file_name, __tmp2.path_template.format(realm_id=realm_id, emoji_file_name=file_name)

    def resize_emoji(__tmp2, __tmp7: __typ0) -> Optional[__typ0]:
        im = Image.open(io.BytesIO(__tmp7))
        format_ = im.format
        if format_ == 'GIF' and im.is_animated:
            return None
        im = ImageOps.fit(im, __tmp2.emoji_size, Image.ANTIALIAS)
        out = io.BytesIO()
        im.save(out, format_)
        return out.getvalue()

    def upload_emoji(__tmp2, realm_id: int, __tmp1: <FILL>,
                     __tmp4) -> Optional[Text]:
        file_name, __tmp11 = __tmp2.get_dst_path_id(realm_id, __tmp1, __tmp4)
        if __tmp1.startswith("/"):
            # Handle relative URLs.
            __tmp1 = urllib.parse.urljoin(settings.EXTERNAL_HOST, __tmp1)
        try:
            __tmp6 = requests.get(__tmp1, stream=True)
        except ConnectionError:
            return None
        if __tmp6.status_code != 200:
            return None
        try:
            __tmp8 = __tmp2.resize_emoji(__tmp6.content)
        except IOError:
            return None
        __tmp2.upload_files(__tmp6, __tmp8, __tmp11)
        return file_name


class LocalUploader(Uploader):
    def __init__(__tmp2) -> None:
        super().__init__()

    @staticmethod
    def mkdirs(path: Text) -> None:
        dirname = os.path.dirname(path)
        if not os.path.isdir(dirname):
            os.makedirs(dirname)

    def write_local_file(__tmp2, path: Text, __tmp9: __typ0) -> None:
        __tmp2.mkdirs(path)
        with open(path, 'wb') as f:
            f.write(__tmp9)

    def upload_files(__tmp2, __tmp6: __typ1, __tmp8: __typ0,
                     __tmp11: Text) -> None:
        dst_file = os.path.join(settings.LOCAL_UPLOADS_DIR, 'avatars', __tmp11)
        if __tmp8:
            __tmp2.write_local_file(dst_file, __tmp8)
        else:
            __tmp2.write_local_file(dst_file, __tmp6.content)
        __tmp2.write_local_file('.'.join((dst_file, 'original')), __tmp6.content)


class S3Uploader(Uploader):
    def __init__(__tmp2) -> None:
        super().__init__()
        conn = S3Connection(settings.S3_KEY, settings.S3_SECRET_KEY)
        bucket_name = settings.S3_AVATAR_BUCKET
        __tmp2.bucket = conn.get_bucket(bucket_name, validate=False)

    def upload_to_s3(__tmp2, path: Text, __tmp9,
                     headers: Optional[Dict[Text, Text]]) -> None:
        key = Key(__tmp2.bucket)
        key.key = path
        key.set_contents_from_string(__tmp5(__tmp9), headers=headers)

    def upload_files(__tmp2, __tmp6, __tmp8: __typ0,
                     __tmp11) -> None:
        headers = None  # type: Optional[Dict[Text, Text]]
        content_type = __tmp6.headers.get(str("Content-Type")) or guess_type(__tmp11)[0]
        if content_type:
            headers = {'Content-Type': content_type}
        if __tmp8:
            __tmp2.upload_to_s3(__tmp11, __tmp8, headers)
        else:
            __tmp2.upload_to_s3(__tmp11, __tmp6.content, headers)
        __tmp2.upload_to_s3('.'.join((__tmp11, 'original')), __tmp6.content, headers)

def get_uploader() -> Uploader:
    if settings.LOCAL_UPLOADS_DIR is None:
        return S3Uploader()
    return LocalUploader()


def __tmp10(__tmp3: StateApps, __tmp0: DatabaseSchemaEditor) -> None:
    realm_emoji_model = __tmp3.get_model('zerver', 'RealmEmoji')
    uploader = get_uploader()  # type: Uploader
    for emoji in realm_emoji_model.objects.all():
        file_name = uploader.upload_emoji(emoji.realm_id, emoji.img_url, emoji.name)
        if file_name is None:
            logging.warning("ERROR: Could not download emoji %s; please reupload manually" %
                            (emoji,))
        emoji.file_name = file_name
        emoji.save()


class Migration(migrations.Migration):
    dependencies = [
        ('zerver', '0076_userprofile_emojiset'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmemoji',
            name='file_name',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.RunPython(__tmp10),
        migrations.RemoveField(
            model_name='realmemoji',
            name='img_url',
        ),
    ]
