# -*- coding: utf-8 -*-
import urllib

from zerver.lib.test_classes import WebhookTestCase

class __typ0(WebhookTestCase):
    STREAM_NAME = 'solano labs'
    URL_TEMPLATE = u"/api/v1/external/solano?api_key={api_key}&stream={stream}"
    FIXTURE_DIR_NAME = 'solano'

    def __tmp3(__tmp1) :
        """
        Build notifications are generated by Solano Labs after build completes.
        """
        expected_topic = u'build update'
        expected_message = (u"Author: solano-ci[bot]@users.noreply.github.com\n"
                            u"Commit: [5f438401eb7cc7268cbc28438bfa70bb99f48a03]"
                            u"(github.com/fazerlicourice7/solano/commit/5f438401eb7cc7268"
                            u"cbc28438bfa70bb99f48a03)\nBuild status: failed :thumbs_down:\n"
                            u"[Build Log](https://ci.solanolabs.com:443/reports/3316175)")

        __tmp1.send_and_test_stream_message('build_001', expected_topic, expected_message,
                                          content_type="application/x-www-form-urlencoded")

    def __tmp2(__tmp1) :
        """
        Build notifications are generated by Solano Labs after build completes.
        """
        expected_topic = u'build update'
        expected_message = (u"Author: Unknown\nCommit: [5d0b92e26448a9e91db794bfed4b8c3556eabc4e]"
                            u"(bitbucket.org/fazerlicourice7/test/commits/5d0b92e26448a9e91db794bfed"
                            u"4b8c3556eabc4e)\nBuild status: failed :thumbs_down:\n"
                            u"[Build Log](https://ci.solanolabs.com:443/reports/3316723)")

        __tmp1.send_and_test_stream_message('build_002', expected_topic, expected_message,
                                          content_type="application/x-www-form-urlencoded")

    def __tmp5(__tmp1) :
        """
        Build notifications are generated by Solano Labs after build completes.
        """
        expected_topic = u'build update'
        expected_message = (u"Author: solano-ci[bot]@users.noreply.github.com\n"
                            u"Commit: [191d34f9da8ff7279b051cd68e44223253e18408]"
                            u"(github.com/anirudhjain75/scipy/commit/191d34f9da8ff7279b051cd"
                            u"68e44223253e18408)\nBuild status: running :arrows_counterclockwise:\n"
                            u"[Build Log](https://ci.solanolabs.com:443/reports/3317799)")

        __tmp1.send_and_test_stream_message('received', expected_topic, expected_message,
                                          content_type="application/x-www-form-urlencoded")

    def test_solano_test_message(__tmp1) :
        expected_topic = u'build update'
        expected_message = "Solano webhook set up correctly"

        __tmp1.send_and_test_stream_message('test', expected_topic, expected_message,
                                          content_type="application/x-www-form-urlencoded")

    def __tmp0(__tmp1, __tmp4: <FILL>) :
        return __tmp1.webhook_fixture_data(__tmp1.FIXTURE_DIR_NAME, __tmp4, file_type="json")
