from typing import TypeAlias
__typ0 : TypeAlias = "bool"
import re
import sys

from typing import Any, Optional, Tuple, Sequence, MutableSequence, List, MutableMapping, IO
from types import ModuleType


# Type Alias for Signatures
Sig = Tuple[str, str]


def parse_signature(__tmp8: str) -> Optional[Tuple[str,
                                                List[str],
                                                List[str]]]:
    m = re.match(r'([.a-zA-Z0-9_]+)\(([^)]*)\)', __tmp8)
    if not m:
        return None
    name = m.group(1)
    name = name.split('.')[-1]
    arg_string = m.group(2)
    if not arg_string.strip():
        return (name, [], [])
    args = [arg.strip() for arg in arg_string.split(',')]
    __tmp6 = []
    __tmp1 = []
    i = 0
    while i < len(args):
        if args[i].startswith('[') or '=' in args[i]:
            break
        __tmp6.append(args[i].rstrip('['))
        i += 1
        if args[i - 1].endswith('['):
            break
    while i < len(args):
        arg = args[i]
        arg = arg.strip('[]')
        arg = arg.split('=')[0]
        __tmp1.append(arg)
        i += 1
    return (name, __tmp6, __tmp1)


def build_signature(__tmp6: Sequence[str],
                    __tmp1) :
    args = []  # type: MutableSequence[str]
    args.extend(__tmp6)
    for arg in __tmp1:
        if arg.startswith('*'):
            args.append(arg)
        else:
            args.append('%s=...' % arg)
    __tmp8 = '(%s)' % ', '.join(args)
    # Ad-hoc fixes.
    __tmp8 = __tmp8.replace('(self)', '')
    return __tmp8


def __tmp5(__tmp4: Sequence[str]) -> Tuple[List[Sig],
                                                        List[Sig]]:
    sigs = []
    class_sigs = []
    for line in __tmp4:
        line = line.strip()
        m = re.match(r'\.\. *(function|method|class) *:: *[a-zA-Z_]', line)
        if m:
            __tmp8 = line.split('::')[1].strip()
            parsed = parse_signature(__tmp8)
            if parsed:
                name, __tmp6, __tmp1 = parsed
                if m.group(1) != 'class':
                    sigs.append((name, build_signature(__tmp6, __tmp1)))
                else:
                    class_sigs.append((name, build_signature(__tmp6, __tmp1)))

    return sorted(sigs), sorted(class_sigs)


def __tmp2(sigs: Sequence[Sig]) -> List[Sig]:
    sig_map = {}  # type: MutableMapping[str, List[str]]
    for name, __tmp8 in sigs:
        sig_map.setdefault(name, []).append(__tmp8)
    result = []
    for name, name_sigs in sig_map.items():
        if len(set(name_sigs)) == 1:
            result.append((name, name_sigs[0]))
    return sorted(result)


def is_c_module(__tmp3: ModuleType) -> __typ0:
    return '__file__' not in __tmp3.__dict__ or __tmp3.__dict__['__file__'].endswith('.so')


def __tmp7(file, module_name: Optional[str] = None,
                 pyversion: Tuple[int, int] = (3, 5)) -> None:
    if module_name:
        if pyversion[0] >= 3:
            version = '%d.%d' % (sys.version_info.major,
                                 sys.version_info.minor)
        else:
            version = '2'
        file.write('# Stubs for %s (Python %s)\n' % (module_name, version))
    file.write(
        '#\n'
        '# NOTE: This dynamically typed stub was automatically generated by stubgen.\n\n')


def __tmp0(docstr: str, name: <FILL>) -> Optional[str]:
    if not docstr:
        return None
    docstr = docstr.lstrip()
    m = re.match(r'%s(\([a-zA-Z0-9_=, ]*\))' % name, docstr)
    if m:
        return m.group(1)
    else:
        return None
