from typing import TypeAlias
__typ0 : TypeAlias = "Text"
__typ1 : TypeAlias = "int"
__typ6 : TypeAlias = "bytes"
__typ3 : TypeAlias = "str"
__typ2 : TypeAlias = "StateApps"
# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:23

import io
import logging
import os
import urllib
from mimetypes import guess_type
from typing import Dict, Optional, Text, Tuple, Union

import requests
from boto.s3.connection import S3Connection
from boto.s3.key import Key
from django.conf import settings
from django.db import migrations, models
from django.db.backends.postgresql_psycopg2.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps
from PIL import Image, ImageOps
from requests import ConnectionError, Response

def __tmp3(s: Union[__typ0, __typ6], encoding: __typ0='utf-8') -> __typ3:
    """converts a string to a native string"""
    if isinstance(s, __typ3):
        return s
    elif isinstance(s, __typ0):
        return s.encode(__typ3(encoding))
    elif isinstance(s, __typ6):
        return s.decode(encoding)
    else:
        raise TypeError("force_str expects a string type")


class __typ5:
    def __init__(__tmp1) -> None:
        __tmp1.path_template = "{realm_id}/emoji/{emoji_file_name}"
        __tmp1.emoji_size = (64, 64)

    def upload_files(__tmp1, response: <FILL>, resized_image: __typ6,
                     __tmp6) -> None:
        raise NotImplementedError()

    def get_dst_path_id(__tmp1, realm_id: __typ1, url: __typ0, __tmp2) :
        _, image_ext = os.path.splitext(url)
        file_name = ''.join((__tmp2, image_ext))
        return file_name, __tmp1.path_template.format(realm_id=realm_id, emoji_file_name=file_name)

    def resize_emoji(__tmp1, image_data: __typ6) -> Optional[__typ6]:
        im = Image.open(io.BytesIO(image_data))
        format_ = im.format
        if format_ == 'GIF' and im.is_animated:
            return None
        im = ImageOps.fit(im, __tmp1.emoji_size, Image.ANTIALIAS)
        out = io.BytesIO()
        im.save(out, format_)
        return out.getvalue()

    def upload_emoji(__tmp1, realm_id: __typ1, __tmp0: __typ0,
                     __tmp2: __typ0) -> Optional[__typ0]:
        file_name, __tmp6 = __tmp1.get_dst_path_id(realm_id, __tmp0, __tmp2)
        if __tmp0.startswith("/"):
            # Handle relative URLs.
            __tmp0 = urllib.parse.urljoin(settings.EXTERNAL_HOST, __tmp0)
        try:
            response = requests.get(__tmp0, stream=True)
        except ConnectionError:
            return None
        if response.status_code != 200:
            return None
        try:
            resized_image = __tmp1.resize_emoji(response.content)
        except IOError:
            return None
        __tmp1.upload_files(response, resized_image, __tmp6)
        return file_name


class __typ4(__typ5):
    def __init__(__tmp1) -> None:
        super().__init__()

    @staticmethod
    def mkdirs(path: __typ0) -> None:
        dirname = os.path.dirname(path)
        if not os.path.isdir(dirname):
            os.makedirs(dirname)

    def write_local_file(__tmp1, path: __typ0, __tmp4: __typ6) -> None:
        __tmp1.mkdirs(path)
        with open(path, 'wb') as f:
            f.write(__tmp4)

    def upload_files(__tmp1, response, resized_image: __typ6,
                     __tmp6: __typ0) -> None:
        dst_file = os.path.join(settings.LOCAL_UPLOADS_DIR, 'avatars', __tmp6)
        if resized_image:
            __tmp1.write_local_file(dst_file, resized_image)
        else:
            __tmp1.write_local_file(dst_file, response.content)
        __tmp1.write_local_file('.'.join((dst_file, 'original')), response.content)


class __typ7(__typ5):
    def __init__(__tmp1) -> None:
        super().__init__()
        conn = S3Connection(settings.S3_KEY, settings.S3_SECRET_KEY)
        bucket_name = settings.S3_AVATAR_BUCKET
        __tmp1.bucket = conn.get_bucket(bucket_name, validate=False)

    def upload_to_s3(__tmp1, path: __typ0, __tmp4,
                     headers: Optional[Dict[__typ0, __typ0]]) -> None:
        key = Key(__tmp1.bucket)
        key.key = path
        key.set_contents_from_string(__tmp3(__tmp4), headers=headers)

    def upload_files(__tmp1, response: Response, resized_image,
                     __tmp6: __typ0) -> None:
        headers = None  # type: Optional[Dict[Text, Text]]
        content_type = response.headers.get(__typ3("Content-Type")) or guess_type(__tmp6)[0]
        if content_type:
            headers = {'Content-Type': content_type}
        if resized_image:
            __tmp1.upload_to_s3(__tmp6, resized_image, headers)
        else:
            __tmp1.upload_to_s3(__tmp6, response.content, headers)
        __tmp1.upload_to_s3('.'.join((__tmp6, 'original')), response.content, headers)

def get_uploader() -> __typ5:
    if settings.LOCAL_UPLOADS_DIR is None:
        return __typ7()
    return __typ4()


def __tmp5(apps, schema_editor) -> None:
    realm_emoji_model = apps.get_model('zerver', 'RealmEmoji')
    uploader = get_uploader()  # type: Uploader
    for emoji in realm_emoji_model.objects.all():
        file_name = uploader.upload_emoji(emoji.realm_id, emoji.img_url, emoji.name)
        if file_name is None:
            logging.warning("ERROR: Could not download emoji %s; please reupload manually" %
                            (emoji,))
        emoji.file_name = file_name
        emoji.save()


class Migration(migrations.Migration):
    dependencies = [
        ('zerver', '0076_userprofile_emojiset'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmemoji',
            name='file_name',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.RunPython(__tmp5),
        migrations.RemoveField(
            model_name='realmemoji',
            name='img_url',
        ),
    ]
