wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.37.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706845665.634308
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 83
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.16.0
      6: 4.37.0
      8:
      - 5
      13: linux-x86_64
